name: CI - Docker FastAPI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and start services
      run: docker compose up --build -d

    - name: Wait for healthcheck
      run: |
        for i in {1..10}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -q))
          if [ "$STATUS" = "healthy" ]; then
            echo "✅ Service is healthy!"
            exit 0
          fi
          echo "⏳ Waiting for container health... attempt $i"
          sleep 5
        done
        echo "❌ Container did not become healthy"
        docker logs $(docker ps -q)
        exit 1

    - name: Stop services
      if: always()
      run: docker compose down
